# Generated by Django 4.0.1 on 2022-01-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dl_code', models.CharField(max_length=8, unique=True, verbose_name='Код договора')),
                ('dl_status', models.BooleanField(verbose_name='Статус активности')),
                ('dl_vsp', models.CharField(max_length=8, verbose_name='Код ВСП')),
                ('dl_number', models.CharField(max_length=128, verbose_name='Номер договора')),
                ('dl_clnt', models.CharField(max_length=128, verbose_name='Контрагент')),
                ('dl_address', models.CharField(max_length=128, verbose_name='Адрес')),
                ('dl_type', models.CharField(max_length=32, verbose_name='Тип договора')),
                ('dl_sqm', models.DecimalField(decimal_places=2, max_digits=2, max_length=11, verbose_name='Площадь кв.м.')),
                ('dl_prc_persqm', models.DecimalField(decimal_places=2, max_digits=2, max_length=11, verbose_name='Цена за кв.м.')),
                ('dl_prc_permnt', models.DecimalField(decimal_places=2, max_digits=2, max_length=11, verbose_name='Цена в месяц')),
                ('dl_dt_start', models.DateField(verbose_name='Дата начала')),
                ('dl_dt_finish', models.DateField(verbose_name='Дата завершения')),
                ('dl_dt_lastmod', models.DateField(auto_now=True, verbose_name='Дата модификации')),
                ('dl_note', models.TextField(verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Договор аренды',
                'verbose_name_plural': 'Договоры аренды',
                'ordering': ['dl_vsp'],
            },
        ),
    ]
