# Generated by Django 4.0.1 on 2022-01-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogs',
            name='dl_address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='dl_clnt',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='dl_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Код договора'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='dl_dt_finish',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='dl_dt_lastmod',
            field=models.DateField(auto_now=True, null=True, verbose_name='Дата модификации'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='dl_dt_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='dl_note',
            field=models.TextField(blank=True, null=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='dl_number',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='dl_prc_permnt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, max_length=11, null=True, verbose_name='Цена в месяц'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='dl_prc_persqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, max_length=11, null=True, verbose_name='Цена за кв.м.'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='dl_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, max_length=11, null=True, verbose_name='Площадь кв.м.'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='dl_status',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Статус активности'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='dl_type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Тип договора'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='dl_vsp',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Код ВСП'),
        ),
    ]
