# Generated by Django 4.0.1 on 2022-01-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgls', '0003_alter_dogs_dl_dt_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogs',
            name='dl_dt_finish',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
    ]
