# Generated by Django 4.0.1 on 2022-01-22 16:17

import crs.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crs_model', models.CharField(blank=True, max_length=33, null=True, verbose_name='Модель')),
                ('crs_gosnom', models.CharField(blank=True, max_length=9, null=True, verbose_name='Госномер')),
                ('crs_year', models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(2001), crs.models.max_value_current_year], verbose_name='Год выпуска')),
                ('crs_vin', models.CharField(max_length=17, verbose_name='VIN')),
                ('crs_drive_21', models.PositiveIntegerField(default=0, max_length=512, verbose_name='Пробег 2021')),
                ('crs_drive_22', models.PositiveIntegerField(default=0, max_length=512, verbose_name='Пробег 2022')),
                ('crs_odo_01_km', models.PositiveIntegerField(default=0, max_length=512, verbose_name='Показание одометра №1')),
                ('crs_odo_01_date', models.DecimalField(blank=True, decimal_places=2, max_digits=11, max_length=11, null=True, verbose_name='Площадь кв.м.')),
                ('crs_ssp', models.CharField(blank=True, max_length=512, null=True, verbose_name='ССП')),
                ('crs_sop', models.CharField(blank=True, max_length=512, null=True, verbose_name='Ответственный пользователь')),
                ('crs_note', models.TextField(blank=True, null=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['crs_year'],
            },
        ),
    ]
