# Generated by Django 4.0.1 on 2022-01-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='crs_drive_21',
            field=models.PositiveIntegerField(default=0, verbose_name='Пробег 2021'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='crs_drive_22',
            field=models.PositiveIntegerField(default=0, verbose_name='Пробег 2022'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='crs_odo_01_km',
            field=models.PositiveIntegerField(default=0, verbose_name='Показание одометра №1'),
        ),
    ]
